Prevent memory leaks in staging by adding env var
gregberge/loadable-components pull request #730
Opened 2021-03-30 21:45 UTC by OSamkova

## Summary

clearModuleCache is causing memory leaks in staging. Added optional env var to prevent it.

## Test plan

<img width="853" alt="Screen Shot 2021-03-30 at 5 35 05 PM" src="https://user-images.githubusercontent.com/14313501/113060946-4df97400-917f-11eb-8347-f548b5337ae9.png">

<img width="856" alt="Screen Shot 2021-03-30 at 5 35 37 PM" src="https://user-images.githubusercontent.com/14313501/113061043-708b8d00-917f-11eb-9321-04b527a2a93b.png">

2021-03-30 22:43 UTC, theKashey commented
I would ask you to open the issue first. 
It is absolutely not clear what you gonna fix, why it is a problem and why this change is a solution.

`smartRequire` is expected to clear module cache in dev mode to support hot module replacement, which never happens in the "non-dev" mode.
Adding extra constant(`LOADABLE_KEEP_CACHE)` which has to be enabled in order to clean cache will break the internal "contract" for all existing users and is a breaking change.

There is no way this PR can be merged as is.

2021-03-30 22:44 UTC, theKashey requested changes
More information is needed

2021-04-01 01:02 UTC, OSamkova commented
Made a change and opened an issue as well.

2021-04-02 22:28 UTC, theKashey commented
Then #733 should have been explicitly mentioned in this PR

2021-04-02 22:31 UTC, theKashey commented on packages/server/src/util.js
> +  if (process.env.NODE_ENV !== 'production' || process.env.LOADABLE_KEEP_CACHE !== '1') {
According to the ticket description, this is an __incorrect__ way to fix it, as `process.env.NODE_ENV !== 'production'` is still true, and the only change here - you are adding an ability to cleanup module cache in production is as well.

Pretty sure you want something else

2021-04-02 22:32 UTC, theKashey commented on packages/server/src/util.js
> +  if (process.env.NODE_ENV !== 'production' || process.env.LOADABLE_KEEP_CACHE !== '1') {
What about enabling clean cache only when HRM is enabled?
```suggestion
  if (process.env.NODE_ENV !== 'production' && module.hot) {
```

2021-04-05 21:20 UTC, theKashey commented
While bounding logic to `module.hot` seems to be right and as can move forward with it - there is still no information about the leak itself and why this is a fix.

2021-04-05 21:31 UTC, OSamkova commented
Adding module.hot did work, i checked it today. What kind of information should i provide about the memory leak? Would screenshots work? Without this our staging environment is crashing every 20 minutes or so.

2021-04-05 23:10 UTC, theKashey commented
Sounds like there is a memory leak in clearModuleCache, probably related to removing self from the children, creating an orphan -> https://github.com/gregberge/loadable-components/blob/4fb7d6dba5d97d22fade7f8a794b50d6506645af/packages/server/src/util.js#L12

2021-04-06 15:54 UTC, OSamkova commented
so should we move forward with module.hot logic fix?

2021-04-07 04:16 UTC, theKashey commented
Yes. That sounds as a must-have in any case

2021-04-07 04:16 UTC, merged